// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"golang_weekend/final/internal/conf"
	"golang_weekend/final/internal/server/shop"
	"golang_weekend/final/internal/service"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confService *conf.Service, traceTracerProvider trace.TracerProvider, logger log.Logger) (*kratos.App, func(), error) {
	shoppingService := service.NewShoppingService(confService, logger)
	httpServer := shop.NewHTTPServer(server, traceTracerProvider, shoppingService)
	grpcServer := shop.NewGRPCServer(server, traceTracerProvider, shoppingService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
