// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2/log"
	"golang_weekend/final/internal/biz"
	"golang_weekend/final/internal/cache/redis"
	"golang_weekend/final/internal/conf"
	"golang_weekend/final/internal/data"
	"golang_weekend/final/internal/mq/kafka"
	"golang_weekend/final/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confData *conf.Data, cache *conf.Cache, messageQueue *conf.MessageQueue, logger log.Logger) (func(context.Context) error, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	fareRepo := data.NewFareRepo(dataData, logger)
	fareUsecase := biz.NewFareUsecase(fareRepo, logger)
	radixRC3, err := redis.NewRedisClient(cache)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kafkaClient := kafka.NewKafkaClient(messageQueue)
	jobService := service.NewJobService(fareUsecase, radixRC3, kafkaClient, logger)
	v := newApp(jobService)
	return v, func() {
		cleanup()
	}, nil
}
